version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./database/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwe123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
